---
name: Example
on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
  pull_request:
    branches:
      - develop
      - release/**
      - hotfix/**
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deploy"
        required: false
        type: choice
        options:
          - sandbox
          - develop
          - quality_assurance
          - user_acceptance_testing
          - production
env:
  GH_ENV_SBX: "sandbox"
  GH_ENV_DEV: "develop"
  GH_ENV_TST: "quality_assurance"
  GH_ENV_STG: "user_acceptance_testing"
  GH_ENV_PROD: "production"

jobs:
  build:
    uses: mxbp/github-pipelines/.github/workflows/build_node.yml@main
    with:
      version: 18
      install_command: echo install_command
      build_command: echo build_command
      test_command: echo test_command
      publish_command: echo publish_command
      build_dir: ./

  docker:
    uses: mxbp/github-pipelines/.github/workflows/docker.yml@main
