---
name: Build → Deploy
run-name: ${{ github.event.head_commit.message }} 🚀 to ${{ inputs.environment != null && inputs.environment || github.ref_name == 'develop' && 'develop' || 'quality_assurance' }} 💪 @${{ github.actor }}
on:
  push:
    branches:
      - develop
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - develop
      - release/*
      - hotfix/*
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deploy"
        required: false
        type: choice
        options:
          - sandbox
          - develop
          - quality_assurance
          - user_acceptance_testing
          - production
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sample-nodejs:
    name: NodeJS
    uses: mxbp/github-pipelines/.github/workflows/node_apprunner.yml@main
    with:
      node_version: 18
      environment: ${{ inputs.environment }}
      sandbox_environment: sandbox
      develop_environment: develop
      test_environment: quality_assurance
      stage_environment: user_acceptance_testing
      production_environment: production
      # aws_s3_bucket: test # TODO: Remove
      # aws_role_arn: test # TODO: Remove
    secrets: inherit
