---
name: Docker

on:
  push:
    branches:
      - "develop"
      - "release/*"
    pull_request:
      branches:
        - "develop"
    workflow_dispatch:
      # inputs:
      #   docker_registry:
      #     required: false
      #     default: ghcr.io # ${{ inputs.docker_registry }}
      #     type: string
      #   logLevel:
      #     description: 'Log level'
      #     required: true
      #     default: 'warning'
      #     type: choice
      #     options:
      #     - info
      #     - warning
      #     - debug
      #   tags:
      #     description: 'Test scenario tags'
      #     required: false
      #     type: boolean
      #   environment:
      #     description: 'Environment to run tests against'
      #     type: environment
      #     required: true

jobs:
  build_push:
    name: Build > Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      image_name: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Dependency Review
      #   uses: actions/dependency-review-action@v3
      #   with:
      #     fail-on-severity: high
      # - name: Download build artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: app-source
      #     path: ${{ github.workspace }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Context for Buildx
        run: docker context create ${{ github.event.repository.name }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: ${{ github.event.repository.name }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,suffix=-${{ github.run_number }}
            type=ref,event=pr,suffix=-${{ github.run_number }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to ghcr.io container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.docker_username != null && secrets.docker_username || github.actor }}
          password: ${{ secrets.docker_password != null && secrets.docker_password || secrets.GITHUB_TOKEN }}
      - name: ${{ github.event_name == 'pull_request' && 'Build' || 'Build and Push' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ contains(github.event_name, 'push') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
