---
  name: Docker
  
  on:
    push:
      branches:
        - "develop"
        - "release/**"
    pull_request:
      branches:
        - "develop"
        - "main"
    workflow_dispatch:
  
  jobs:
    build_push:
      name: Build > Push
      runs-on: ubuntu-latest
      permissions:
        packages: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Debug Info
          run: |
            echo "github.head_ref - ${{ github.head_ref }}"
            echo "github.base_ref - ${{ github.base_ref }}"
            echo "github.ref_name - ${{ github.ref_name }}"
            echo "github.run_number - ${{ github.run_number }}"
            echo "github.run_attempt - ${{ github.run_attempt }}"
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v2
        - name: Setup Docker Context for Buildx
          run: docker context create ${{ github.event.repository.name }}
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
          with:
            version: latest
            endpoint: ${{ github.event.repository.name }}
        - name: Docker Meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ghcr.io/${{ github.repository }}
            tags: |
              type=ref,event=branch,suffix=-${{ github.run_attempt }}
              type=ref,event=pr,suffix=-${{ github.run_attempt }}
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
        - name: Login to ghcr.io container registry
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v2
          with:
            registry: ghcr.io # FIXME: ${{ inputs.docker_registry }}
            username: ${{ secrets.docker_username != null && secrets.docker_username || github.actor }}
            password: ${{ secrets.docker_password != null && secrets.docker_password || secrets.GITHUB_TOKEN }}
        - name: ${{ github.event_name == 'pull_request' && 'Build' || 'Build and Push' }}
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile # FIXME: Make variable
            push: ${{ contains(github.event_name, 'push') }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: VERSION=${GITHUB_REF_NAME##*/}
    create_tag:
      name: Make tag
      runs-on: ubuntu-latest
      if: |
        github.event_name == 'pull_request' && github.event.pull_request.merged == true &&
        github.base_ref == github.event.repository.default_branch &&
        (startsWith(github.head_ref, 'release') || startsWith(github.head_ref, 'hotfix'))
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Set Git tag
          # Settings > Actions > General > Workflow permissions > Read and write permissions
          run: |
            git tag --force "v${GITHUB_HEAD_REF##*/}"
            git push --force --tags