---
name: Example
on:
  push:
    branches:
      - develop
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - develop
      - release/*
      - hotfix/*
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deploy"
        required: false
        type: choice
        options:
          - sandbox
          - develop
          - quality_assurance
          - user_acceptance_testing
          - production
jobs:
  build:
    name: Build
    uses: mxbp/github-pipelines/.github/workflows/build_node.yml@main
    with:
      version: 18
  docker:
    name: Docker
    needs: build
    uses: mxbp/github-pipelines/.github/workflows/docker.yml@main
  deploy:
    name: Deploy
    needs: docker
    if: ${{ !failure() }} && ${{ !cancelled() }}
    uses: mxbp/github-pipelines/.github/workflows/deploy_aws_apprunner.yml@main
    with:
      environment: ${{ inputs.environment }}
      sandbox_environment: sandbox
      develop_environment: develop
      test_environment: quality_assurance
      stage_environment: user_acceptance_testing
      production_environment:  production
