---
name: Docker

on:
  push:
    branches:
      - develop
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_push:
    name: Build > Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Debug Info
        run: |
          echo "github.head_ref - ${{ github.head_ref }}"
          echo "github.base_ref - ${{ github.base_ref }}"
          echo "github.ref_name - ${{ github.ref_name }}"
          echo "github.run_number - ${{ github.run_number }}"
          echo "github.run_attempt - ${{ github.run_attempt }}"
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Context for Buildx
        run: docker context create ${{ github.event.repository.name }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: ${{ github.event.repository.name }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,suffix=-${{ github.run_number }}
            type=ref,event=pr,suffix=-${{ github.run_number }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to ghcr.io container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io # FIXME: ${{ inputs.docker_registry }}
          username: ${{ secrets.docker_username != null && secrets.docker_username || github.actor }}
          password: ${{ secrets.docker_password != null && secrets.docker_password || secrets.GITHUB_TOKEN }}
      - name: ${{ github.event_name == 'pull_request' && 'Build' || 'Build and Push' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile # FIXME: Make variable
          push: ${{ contains(github.event_name, 'push') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${GITHUB_REF_NAME##*/}
      - name: Create/Update PR to 'main'
        if: startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'hotfix')
        # TODO: READMR.md :: Settings > Actions > General > Workflow permissions > Allow GitHub Actions to create and
        # approve pull requests
        run: |
          gh_pr_up() {
            gh pr create --draft "$@" || gh pr edit "$@"
          }
          gh_pr_up \
            --base "main" \
            --title "Release v${GITHUB_REF_NAME##*/}" \
            --body "Created by GitHub Actions"
        env:
          GH_TOKEN: ${{ github.token }}

          ###