---
on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  # TODO: Move to workflow_dispatch input
  MAIN_BRANCH_NAME: main

jobs:
  create_tag:
    name: Create tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
      - name: Debug Info
        run: |
          echo "github.head_ref - ${{ github.head_ref }}"
          echo "github.base_ref - ${{ github.base_ref }}"
          echo "github.ref_name - ${{ github.ref_name }}"
          echo "github.run_number - ${{ github.run_number }}"
          echo "github.run_attempt - ${{ github.run_attempt }}"
      - name: Set Git user name and email
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions-bot@github.com"
      - name: Set Git tag
        # TODO: READMR.md :: Settings > Actions > General > Workflow permissions > Read and write permissions
        run: |
          git tag --force --message="v${GITHUB_HEAD_REF##*/}" "v${GITHUB_HEAD_REF##*/}"
          git push --force --tags
        # TODO: Mark develop branch as default branch
      - name: Merge branch '${{ github.ref_name }}' into '${{ github.event.repository.default_branch }}'
        run: |
          git fetch --unshallow
          git checkout ${{ github.event.repository.default_branch }}
          git pull
          git merge \
            --no-ff $MAIN_BRANCH_NAME \
            --message="Auto-Merge branch ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          git push
      - name: Create Release
        run: gh release create "v${GITHUB_HEAD_REF##*/}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
        # id: create_release
        # uses: actions/create-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tag_name: ${{ steps.tag.outputs.tag }}
        #   release_name: ${{ steps.tag.outputs.tag }}
        #   draft: false
        #   prerelease: false

      # Create PR
      # - name: pull-request
      #   run: |
      #     gh_pr_up() { gh pr create $* || gh pr edit $* }
      #     gh_pr_up --title "My pull request" --body "Description"
